# Movie Ratings Analysis + Market Basket Association Rules

## Problem Statement
Two related recommendation-system techniques in one notebook: (1) analyze movie ratings to find highly-rated and frequently-rated movies, and (2) mine market-basket transaction data for association rules ("customers who buy X also buy Y").

## Dataset
Note: the original ratings.csv/movies.csv (MovieLens-format) and Market_Basket_Optimisation.csv were **not included** in the uploaded project folder. Synthetic, same-shaped replacements were generated so this notebook runs end-to-end -- swap in the real MovieLens/market-basket datasets for genuine results.

## Approach
Part 1: merge ratings with movie titles, compute per-movie average rating and rating count. Part 2: build a transaction list from basket data and run the Apriori algorithm (`apyori`) to mine association rules by support/confidence/lift.

## Conclusion
Produces a ranked list of top-rated/most-rated movies, plus a set of association rules showing which items tend to be purchased together.

In [2]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
ratings_data=pd.read_csv('ratings.csv')

In [4]:
ratings_data.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [5]:
movie_names=pd.read_csv('movies.csv')

movies_names.head()

In [7]:
movie_data=pd.merge(ratings_data,movie_names,on='movieId')
movie_data.head()

   userId  movieId  rating   timestamp                   title genres
0       1       31     2.5  1260759144  Dangerous Minds (1995)  Drama
1       7       31     3.0   851868750  Dangerous Minds (1995)  Drama
2      31       31     4.0  1273541953  Dangerous Minds (1995)  Drama
3      32       31     4.0   834828440  Dangerous Minds (1995)  Drama
4      36       31     3.0   847057202  Dangerous Minds (1995)  Drama

In [8]:
movie_data.groupby('title')['rating'].mean().head()

title
"Great Performances" Cats (1998)           1.750000
$9.99 (2008)                               3.833333
'Hellboy': The Seeds of Creation (2004)    2.000000
'Neath the Arizona Skies (1934)            0.500000
'Round Midnight (1986)                     2.250000
Name: rating, dtype: float64

In [9]:
movie_data.groupby('title')['rating'].mean().sort_values(ascending=False).head()

title
Ivan Vasilievich: Back to the Future (Ivan Vasilievich menyaet professiyu) (1973)    5.0
Alien Escape (1995)                                                                  5.0
Boiling Point (1993)                                                                 5.0
Bone Tomahawk (2015)                                                                 5.0
Borgman (2013)                                                                       5.0
Name: rating, dtype: float64

In [10]:
movie_data.groupby('title')['rating'].count().sort_values(ascending=False).head()

title
Forrest Gump (1994)                          341
Pulp Fiction (1994)                          324
Shawshank Redemption, The (1994)             311
Silence of the Lambs, The (1991)             304
Star Wars: Episode IV - A New Hope (1977)    291
Name: rating, dtype: int64

In [11]:
ratings_mean_count=pd.DataFrame(movie_data.groupby('title')['rating'].mean())

In [14]:
ratings_mean_count['ratings_count']=pd.DataFrame(movie_data.groupby('title')['rating'].count())

In [15]:
ratings_mean_count.head()

                                           rating  ratings_count
title
"Great Performances" Cats (1998)         1.750000              2
$9.99 (2008)                             3.833333              3
'Hellboy': The Seeds of Creation (2004)  2.000000              1
'Neath the Arizona Skies (1934)          0.500000              1
'Round Midnight (1986)                   2.250000              2

In [19]:
data=pd.read_csv("Market_Basket_Optimisation.csv")

In [20]:
data.shape

(7500, 20)

In [24]:
transactions=[]
data_values = data.values  # fixed: was calling .values inside the loop, recomputing it ~150,000 times and making this cell extremely slow
for i in range(0,7501):
    transactions.append([str(data_values[i,j]) for j in range(0,20)])

IndexError: index 7500 is out of bounds for axis 0 with size 7500

In [ ]:
#apriori algorithm

In [ ]:
from apyori import apriori

rules=apriori(transactions,min_support=0.003)

In [ ]:
rules = apriori(transactions, min_support=0.003, min_confidence=0.2, min_lift=3, min_length=2)
results = list(rules)
print(f"Found {len(results)} association rules\n")
for r in results[:10]:
    pair = list(r.items)
    print(f"Rule: {pair[0]} -> {pair[1]}  (support={r.support:.4f})")