# Pandas: Series & DataFrame Basics

Introduction to Pandas' two core data structures.

**Covers:**
- Creating and indexing Series and DataFrames
- Basic DataFrame operations

In [1]:
#Pandas --- Packages
#managing data Pandas is used
#data types ---- Series(Similar type of data), Dataframe(collection of different type of series).
#series - is cloumn in a dataframe is called series  (like excel).
#Dataframe - Multiple series is dataframe like complete sheet.

In [2]:
import pandas as pd
import numpy as np

In [3]:
#creating series
#from list
#from arrays

In [4]:
#from list
list1 = [1,2,3,4]
array1 = np.array(list1)

In [5]:
s1 = pd.Series(data = list1)
s2 = pd.Series(data = array1)

In [6]:
labels = ['r0','r1','r3','r4']
lb = ['1','2','3','4']
s3 = pd.Series(data = list1,index = labels)
s4 = pd.Series(s2,lb)
#s3 = pd.Series(list1,labels)

In [7]:
#Access data from series
#row labels
print(s3)
print(s4)

r0    1
r1    2
r3    3
r4    4
dtype: int64
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [8]:
print(s3['r3'])

3

In [9]:
s3[2] = 100
print(s3)

r0      1
r1      2
r3    100
r4      4
dtype: int64

C:\Users\maham\AppData\Local\Temp\ipykernel_3024\1211838197.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s3[2] = 100

In [10]:
data1 = pd.Series(data=[1,2,3],index = ['a','b','c'])
data2 = pd.Series(data = [1,2,3,4], index = ['a','f','c','b'])

In [11]:
print(data1)

a    1
b    2
c    3
dtype: int64

In [12]:
print(data2)

a    1
f    2
c    3
b    4
dtype: int64

In [13]:
#Linear algreba
#we can add but same label will do one time

print(data1 + data2)

a    2.0
b    6.0
c    6.0
f    NaN
dtype: float64

In [14]:
print(data1 - data2)

a    0.0
b   -2.0
c    0.0
f    NaN
dtype: float64

In [15]:
print(data1 * data2)
print()
print(data1 / data2)

a    1.0
b    8.0
c    9.0
f    NaN
dtype: float64

a    1.0
b    0.5
c    1.0
f    NaN
dtype: float64

In [16]:
#combining of series
#Row wise (axix = 0)
#column wise (axis = 1)
result1 = pd.concat([data1,data2] ,axis = 0)
print(result1)

a    1
b    2
c    3
a    1
f    2
c    3
b    4
dtype: int64

In [17]:
#column wise (axis = 1)
result2 = pd.concat([data1,data2] ,axis = 1)
print(result2)

     0  1
a  1.0  1
b  2.0  4
c  3.0  3
f  NaN  2

In [18]:
type(result2)

pandas.core.frame.DataFrame

In [19]:
#Creating a dataframe without adding series
d1 = pd.DataFrame([[1,2,3],[4,5,6]])
print(d1)

   0  1  2
0  1  2  3
1  4  5  6

In [20]:
#from
d2 = pd.DataFrame(np.random.randn(3,2))
print(d2)

          0         1
0 -0.065291 -2.028513
1 -1.023418 -1.247338
2  0.008768  1.481200

In [21]:
d3 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index = ['r0','r1','r3'], columns = ['c0','c1','c2'])

In [22]:
print(d3)

    c0  c1  c2
r0   1   2   3
r1   4   5   6
r3   7   8   9

In [23]:
#Access data
#Access individual series
print(d3['c2'])

r0    3
r1    6
r3    9
Name: c2, dtype: int64

In [24]:
#Access multiple series --dataFrame_name[[]]
print(d3[['c2','c1']])

    c2  c1
r0   3   2
r1   6   5
r3   9   8

In [25]:
#access multiple row from data frame ---dataFrame_name.loc[[]]
print(d3.loc[['r1','r0']])

    c0  c1  c2
r1   4   5   6
r0   1   2   3

In [26]:
d3.shape

(3, 3)

In [27]:
d3["c3"] = [10,20,30]

In [28]:
print(d3['c3'])

r0    10
r1    20
r3    30
Name: c3, dtype: int64

In [29]:
#remove column c1 from d3
#drop - returns a new DataFrame by removinf row/col
#if we use the drop it will not gonna delete from the orginal dataframe
d3.drop('c2',axis = 1)

    c0  c1  c3
r0   1   2  10
r1   4   5  20
r3   7   8  30

In [30]:
#remove c1 from original DataFrame
d3.drop('c2',axis = 1,inplace = True)

In [31]:
print(d3)

    c0  c1  c3
r0   1   2  10
r1   4   5  20
r3   7   8  30

In [32]:
d3.drop('r1',axis = 0,inplace = True)

In [33]:
print(d3)

    c0  c1  c3
r0   1   2  10
r3   7   8  30

In [34]:
#combinig of DataFrame
#joint
#merge

In [35]:
d1 = pd.DataFrame({'customer' : ['a','b','c','d'],'category': ['cat1','cat2','cat3','cat4'],'sales' : [123,456,678,789]},index = [0,1,2,3])

In [36]:
print(d1)

  customer category  sales
0        a     cat1    123
1        b     cat2    456
2        c     cat3    678
3        d     cat4    789

In [37]:
d2=pd.DataFrame({'customer':['a','b','c','d','e'],
                'color':['red','blue','red','red','green'],
                'sales':[123,678,78,345,123],
                'distance':[100,200,300,400,500]},
               index=[4,5,6,7,8])

In [38]:
d2

  customer  color  sales  distance
4        a    red    123       100
5        b   blue    678       200
6        c    red     78       300
7        d    red    345       400
8        e  green    123       500

In [39]:
pd.concat([d1,d2],axis = 0)

  customer category  sales  color  distance
0        a     cat1    123    NaN       NaN
1        b     cat2    456    NaN       NaN
2        c     cat3    678    NaN       NaN
3        d     cat4    789    NaN       NaN
4        a      NaN    123    red     100.0
5        b      NaN    678   blue     200.0
6        c      NaN     78    red     300.0
7        d      NaN    345    red     400.0
8        e      NaN    123  green     500.0

In [40]:
pd.concat([d1,d2],axis = 1)

  customer category  sales customer  color  sales  distance
0        a     cat1  123.0      NaN    NaN    NaN       NaN
1        b     cat2  456.0      NaN    NaN    NaN       NaN
2        c     cat3  678.0      NaN    NaN    NaN       NaN
3        d     cat4  789.0      NaN    NaN    NaN       NaN
4      NaN      NaN    NaN        a    red  123.0     100.0
5      NaN      NaN    NaN        b   blue  678.0     200.0
6      NaN      NaN    NaN        c    red   78.0     300.0
7      NaN      NaN    NaN        d    red  345.0     400.0
8      NaN      NaN    NaN        e  green  123.0     500.0