# Pandas: Merge, Join & Column Operations

Combining DataFrames and common column-level operations.

**Covers:**
- `merge()` (inner/outer/left/right) vs. `join()` (index-based)
- Column methods: `.unique()`, `.value_counts()`, `.apply()`, `.sort_values()`
- `groupby()` for aggregation
- Reading/writing CSV and Excel files

In [1]:
#Pandas
import pandas as pd
import numpy as np

In [2]:
#combining data frames
#Merge and join operator
#Merge ---combines dataframe using a column's values.
#join --- combines dataframe using index. (using common row label(inner,outer,left,right join))
d1 = pd.DataFrame({'A': [1,2,3], 'B':[100,200,300], 'C': [1,90,10]}, index = ['r0','r1','r2'])

In [4]:
d2 = pd.DataFrame({'A': [1,2,33], 'C':[10,6,9],'E': [1,2,4] }, index = ['r0','r1','r2'])

In [5]:
print(d1)

    A    B   C
r0  1  100   1
r1  2  200  90
r2  3  300  10

In [6]:
print(d2)

     A   C  E
r0   1  10  1
r1   2   6  2
r2  33   9  4

In [10]:
#merge 
pd.merge(d1,d2, how = 'inner',on = 'A')

   A    B  C_x  C_y  E
0  1  100    1   10  1
1  2  200   90    6  2

In [11]:
pd.merge(d1,d2, how = 'outer',on = 'A')

    A      B   C_x   C_y    E
0   1  100.0   1.0  10.0  1.0
1   2  200.0  90.0   6.0  2.0
2   3  300.0  10.0   NaN  NaN
3  33    NaN   NaN   9.0  4.0

In [12]:
pd.merge(d1,d2, how = 'right',on = 'A')

    A      B   C_x  C_y  E
0   1  100.0   1.0   10  1
1   2  200.0  90.0    6  2
2  33    NaN   NaN    9  4

In [13]:
pd.merge(d1,d2, how = 'left',on = 'A')

   A    B  C_x   C_y    E
0  1  100    1  10.0  1.0
1  2  200   90   6.0  2.0
2  3  300   10   NaN  NaN

In [19]:
d1 = pd.DataFrame({'Q1' : [1,2,3],'Q2' : [1,3,5]},index = ['r1','r2','r3'])

In [20]:
d2 = pd.DataFrame({'Q3' : [1,2,3], 'Q4' : [1,2,3]}, index = ['r1','r2','r3'])

In [21]:
d1.join(d2, how = 'inner')

    Q1  Q2  Q3  Q4
r1   1   1   1   1
r2   2   3   2   2
r3   3   5   3   3

In [22]:
d3 = pd.DataFrame({'color' : ['red','blue','red','red', 'yellow'], 'price' : [100,200,100,300,400]})

In [23]:
print(d3)

    color  price
0     red    100
1    blue    200
2     red    100
3     red    300
4  yellow    400

In [24]:
d3

    color  price
0     red    100
1    blue    200
2     red    100
3     red    300
4  yellow    400

In [26]:
d3['color'].unique()

array(['red', 'blue', 'yellow'], dtype=object)

In [27]:
d3['color'].value_counts

<bound method IndexOpsMixin.value_counts of 0       red
1      blue
2       red
3       red
4    yellow
Name: color, dtype: object>

In [28]:
d3['price'].sum()

1100

In [29]:
d3['price'].mean()

220.0

In [33]:
def sample(s):
    return s*0.5

In [35]:
#apply --- used to apply a user defined function to dataframe
d3['price'].apply(sample)

0     50.0
1    100.0
2     50.0
3    150.0
4    200.0
Name: price, dtype: float64

In [44]:
d3.sort_values(by = 'price', inplace = True) # If we don't use inplace then new dataframe will be created.
#The default values of this attribute is False and it returns the copy of the object.
print(d3)

    color  price
0     red    100
2     red    100
1    blue    200
3     red    300
4  yellow    400

In [47]:
d3.sort_values(by = 'price', inplace = True, ascending= 0) 
print(d3)

    color  price
4  yellow    400
3     red    300
1    blue    200
0     red    100
2     red    100

In [48]:
#grouping
data = pd.DataFrame({'customer' : ['c1', 'c1', 'c2', 'c2', 'c3', 'c3'], 'product1' : [1,2,3,4,5,6], 'proudct2' : [10,20,30,40,50,60]})

In [49]:
print(data)

  customer  product1  proudct2
0       c1         1        10
1       c1         2        20
2       c2         3        30
3       c2         4        40
4       c3         5        50
5       c3         6        60

In [56]:
d = data.groupby('customer')

In [58]:
print(d)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001F7622D9AC0>

In [59]:
d.mean()

          product1  proudct2
customer
c1             1.5      15.0
c2             3.5      35.0
c3             5.5      55.0

In [ ]:
#csv files
#excel

In [60]:
#save dataframe to a csv file
#if we want to index value then we will use index = True
data.to_csv('dataframe1.csv',index=True)

In [67]:
#import csv
#read contents of csv file as a dataframe
d1 = pd.read_csv('dataframe1.csv')

In [69]:
print(d1)

   Unnamed: 0 customer  product1  proudct2
0           0       c1         1        10
1           1       c1         2        20
2           2       c2         3        30
3           3       c2         4        40
4           4       c3         5        50
5           5       c3         6        60

In [72]:
#save dataframe to excel speadsheet
data.to_excel('dataframe.xlsx', index = False, sheet_name='first_sheet')

In [73]:
d2 = pd.read_excel('dataframe.xlsx',sheet_name='first_sheet')

In [74]:
print(d2)

  customer  product1  proudct2
0       c1         1        10
1       c1         2        20
2       c2         3        30
3       c2         4        40
4       c3         5        50
5       c3         6        60

In [ ]:
#Assignment

In [ ]:
'''1. You are a data analyst at a retail company. 
The company has collected data on their sales transactions
and wants you to analyze and sort this data to gain 
insights into the performance of their products. 
The data is provided in the following format: 
Aswathi Sasidharan says:+----------+-----------+----------+-------+------------+
| Order_ID | Product   | Quantity | Price | Order_Date |
+----------+-----------+----------+-------+------------+
| 1001     | Apples    | 10       | 0.50  | 2023-06-01 |
| 1002     | Bananas   | 5        | 0.30  | 2023-06-02 |
| 1003     | Cherries  | 20       | 1.50  | 2023-06-01 |
| 1004     | Apples    | 8        | 0.55  | 2023-06-03 |
| 1005     | Bananas   | 15       | 0.25  | 2023-06-03 |
| 1006     | Cherries  | 25       | 1.40  | 2023-06-02 |
| 1007     | Apples    | 10       | 0.60  | 2023-06-02 |
| 1008     | Bananas   | 10       | 0.35  | 2023-06-01 |
+----------+-----------+----------+-------+------------+ 
Tasks
Load the Data: Create a pandas DataFrame from the provided data.
Calculate Total Sales: Add a new column Total_Sales to the DataFrame, 
which is calculated as Quantity * Price.
Sort by Total Sales: Sort the DataFrame by 
Total_Sales in descending order.
Sort by Product and Order Date: 
Sort the DataFrame first by Product and 
then by Order_Date in ascending order.
Find Top Selling Product: Identify the product
with the highest total sales.
Group by Product: Group the data by Product 
and calculate the total quantity sold for each product. 
'''

In [ ]:
#The packages which we have to work date and time,os,regular expressions